project:
  type: website
  output-dir: docs

website:
  title: "Home"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/skj092
      - icon: twitter
        href: https://twitter.com/Sonu_Kumar_Jha
format:
  html:
    theme: cosmo
    css: styles.css



