project:
  type: website
  output-dir: docs

website:
  title: "Home"
  site-url: https://sonujha.tech
  description: "Another data science student’s blogs"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/skj092
      - icon: twitter
        href: https://twitter.com/Sonu_Kumar_Jha
      - icon: rss
        href: index.xml
format:
  html:
    theme:
      dark: darkly
    css: styles.css



