---
title: "About Me"
about:
  template: solana
  links:
    - icon: twitter
      text: Twitter
      href: https://twitter.com/WanderingByte
    - icon: linkedin
      text: LinkedIn
      href: https://www.linkedin.com/in/sonujha092/
    - icon: github
      text: Github
      href: https://github.com/skj092
---



Hello! I'm Sonu Jha, an AI Engineer with a passion for leveraging cutting-edge technology to solve complex problems. With a background in Mathematics and extensive experience in Machine Learning and Computer Vision, I'm constantly exploring the frontiers of Artificial Intelligence.

## Professional Journey

Currently, I'm working as an AI Engineer at Signzy Technology in Bangalore, where I've had the opportunity to work on exciting projects such as:

- Developing an Aadhaar Masker using advanced image segmentation techniques
- Creating a forgery detection system for identity documents
- Implementing salary slip extraction using Langchain and GenerativeAI
- Building a signature verification model using Siamese Architecture

Prior to this, I worked as an Associate Software Developer at Accenture Solution in Mumbai, where I honed my skills in data analysis and web development.

## Technical Expertise

My expertise lies in:

- Machine Learning and Deep Learning (PyTorch, Keras, FastAI, Hugging Face)
- Computer Vision tasks (Image Classification, Object Detection, Image Segmentation)
- Natural Language Processing (NLP) and Understanding (NLU)
- API development (FastAPI, Falcon, Node.js, Javascript)
- DevOps tools (Docker, CI/CD, Grafana, Kibana)

I'm particularly excited about the potential of Generative AI and have been integrating tools like Langchain, GPT, and Bard to improve AI microservices.

## Achievements and Interests

I'm proud to have secured a bronze medal in the UBC Ovarian Cancer Subtype Classification competition on Kaggle. I've also been recognized for my work in improving AI service accuracy through the integration of Generative AI at Signzy Technology.

Beyond the world of AI, I have a keen interest in mountaineering and have completed a Basic Mountaineering Course from the National Institute of Mountaineering and Adventure Sports.

## Sharing Knowledge

I believe in the power of education and enjoy sharing my knowledge. I've had the privilege of being invited as a guest lecturer to present on "Application of Mathematics in Machine Learning" at R.D National College in Mumbai.

Through this blog, I aim to share my insights, experiences, and learnings in the field of AI and technology. Whether you're a fellow AI enthusiast, a student of technology, or simply curious about the world of artificial intelligence, I hope you'll find something valuable here.

Feel free to connect with me on [LinkedIn](https://www.linkedin.com/in/sonujha092/) or check out my projects on [GitHub](https://github.com/skj092). Let's explore the exciting world of AI together!
